### ISSUE TITLE
Constant OOM of core Everest components on large-scale nodes.

### ISSUE THREAD

**Issue by sindef** [percona/everest#1274]
Hi,

We have identified that when our Everest nodes schedule onto some of our larger cluster nodes (2T Memory, 112 CPU) we see many database pods in state CrashLoopBackOff due to an OOMKill, we also see this behaviour on smaller cluster nodes with intense database or network activity.

In both instances, the database itself is not reaching a limit, but rather this is caused by the PMM sidecar pods having statically set limits which don't seem to be configurable in any deployment option. Is there a future plan or option to make these limits configurable when databases are deployed via Everest rather than CR (and ideally the requests/limits configurable across the database pods as well, in those instances where we don't necessarily want guaranteed pods for overcommit of resources)?

**Comment by mayankshah1607** [comment]
Hi @sindef 

It is possible to configure the requests/limits of the PMM sidecar via the `DatabaseCluster` CR, like so:

```
kubectl edit databasecluster <YOUR DB NAME> -n <YOUR NAMESPACE>
```

.. and then updating the `.spec.monitoring.resources` section with your desired values, for example:
```yaml
apiVersion: everest.percona.com/v1alpha1
kind: DatabaseCluster
 # ... hidden
  monitoring:
    monitoringConfigName: pmm
    resources:
      limits:
        cpu: 200m
        memory: 200Mi
      requests:
        cpu: 200m
        memory: 200Mi
# ... hidden ...
```
