### ISSUE TITLE
feat: importing existing clusters

### ISSUE THREAD

**Issue by george-pogosyan** [percona/everest#546]
It would be great, if everest could import existing cluster, created with percona's operators when installing a namespace.

**Comment by spron-in** [comment]
@george-pogosyan it is something on our radar. I would appreciate if you can share more about your use case either here or we can jump into a call to discuss it. (feel free to book me here: https://scheduler.zoom.us/percona-sergey-pronin/30-mins)

**Comment by kylemclaren** [comment]
What's blocking this, roughly? Trying to figure out if it would feasible trying to build a shim so we can manage pg-operator instances _from_ Everest.

**Comment by PeterSzcz** [comment]
Hi @kylemclaren 

I don't think anything specific is blocking this feature, we need to make sure the CRDs are compatible when "connecting" existing cluster to Everest and provide UI/API/CLI methods to perform this operation. I think the biggest effort will be to QA this feature for all 3 DB technologies we currently support. One of our priorities for Q1 2025 is ability to "import" databases to Everest from various sources like backups or "downtimeless" using DB replication. We need to discuss internally as another option "connecting" databases managed with operators to Everest.

**Comment by maxisam** [comment]
Hi just wanna check what is the progress on this one? I image Everest should work like ArgoCD. When I add an application directly to kubernetes, ArgoCD pickup that application directly without me doing any import operation. With that, we can perfectly work with GitOps, otherwise we need to create a way to backup Everest. Ideal way for us to use Everest is we create mongodb with CRD yaml that handles by the mongodb operator and Everest just pickup that directly. And users can use Everest to do backup restore operation. 

Honestly I think spending time to work on creation UI in Everest is not really worth it. Nowaday, everyone is using GitOps in kubernetes. Of course it has its value, but IMO, it is not useful in real world usage. It is just not realistic to let users / dev to spin up their own database without asking DevOps engineers. And it is useless for DevOps guys to use UI and we care more about GitOps. It definitely looks cool tho.

Nevertheless, Everest is a great project. Very very cool and impressive. I truly appreciate the team behind it. Thank you!

**Comment by mayankshah1607** [comment]
@maxisam FWIW, Everest provides its [own set of CRDs](https://github.com/percona/everest-operator/tree/main/config/crd/bases), which act as an abstraction over the underlying database operator CRDs. These Everest CRDs are what the API (and by extension, the UI) relies on to manage database resources.

We typically recommend using the API or UI, since they offer built-in validations and safeguards. But if you're aiming for a GitOps-driven workflow, it would be worth considering working directly with these Everest CRDs. With that said, we don't yet have full documentation for them, but you can find several usage examples [here](https://github.com/percona/everest-operator/tree/main/tests/e2e/core).

**Comment by maxisam** [comment]
@mayankshah1607 Thank you for pointing me to a good direction. So you mean, I can somehow import the cluster if I apply correct manifests?

**Comment by mayankshah1607** [comment]
@maxisam It depends on what you mean by "import."

If your goal is to create a database in Everest that mirrors your existing cluster’s configuration—like number of nodes, storage size, engine version, etc.—then yes, creating a similar DatabaseCluster CR is all you need. That’s enough for most use cases.

But, if you also need to import backup data from your existing cluster, that’s a bit more involved -- we’re actively working on streamlining and automating that part.

I suggested using Everest’s CRDs because it sounded like your main goal was to manage everything via GitOps.

**Comment by maxisam** [comment]
I don't think it will work. I tested it and it will wipe my existing cluster's settings

my cluster is like below yaml, but the [database cluster CRD](https://github.com/percona/everest-operator/blob/main/bundle/manifests/everest.percona.com_databaseclusters.yaml) don't have a way to control the detail settings.

If I create one with the same name, it will remove a lot of settings.

some are important to my setup like

- expose externally as node port 
- podSecurityContext, containerSecurityContext


```yml
apiVersion: psmdb.percona.com/v1
kind: PerconaServerMongoDB
metadata:
  finalizers:
    - percona.com/delete-psmdb-pods-in-order
  labels:
    app.kubernetes.io/instance: db-dev
    app.kubernetes.io/managed-by: Helm
    app.kubernetes.io/name: psmdb-db
    app.kubernetes.io/version: 1.19.1
    argocd.argoproj.io/instance: pp-db-dev
    helm.sh/chart: psmdb-db-1.19.1
  name: mongodb-cms
  namespace: dev
spec:
  backup:
    containerSecurityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      seccompProfile:
        type: RuntimeDefault
    enabled: true
    image: percona/percona-backup-mongodb:2.8.0-multi
    pitr:
      enabled: false
    podSecurityContext:
      fsGroup: 2
      fsGroupChangePolicy: OnRootMismatch
      runAsGroup: 2
      runAsNonRoot: true
      runAsUser: 2
    resources:
      limits:
        cpu: 300m
        memory: 1G
      requests:
        cpu: 100m
        memory: 1G
    storages:
      pfb1-s3:
        s3:
          bucket: pp-dev
          credentialsSecret: pfb1-s3
          endpointUrl: https://pfb1.xxx.com
          forcePathStyle: true
          prefix: mongodb-cms-dev
          region: local
        type: s3
    tasks:
      - enabled: true
        keep: 30
        name: backup-cms-dev
        schedule: 0 */6 * * *
        storageName: pfb1-s3
    volumeMounts: []
  clusterServiceDNSMode: External
  crVersion: 1.19.1
  enableVolumeExpansion: false
  image: percona/percona-server-mongodb:8.0.4-1-multi
  imagePullPolicy: Always
  initContainerSecurityContext:
    allowPrivilegeEscalation: false
    capabilities:
      drop:
        - ALL
    seccompProfile:
      type: RuntimeDefault
  multiCluster:
    enabled: false
  pause: false
  replsets:
    - affinity:
        advanced:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - podAffinityTerm:
                  topologyKey: kubernetes.io/hostname
                weight: 1
        antiAffinityTopologyKey: kubernetes.io/hostname
      arbiter:
        affinity:
          antiAffinityTopologyKey: kubernetes.io/hostname
        enabled: false
        size: 0
      configuration: "operationProfiling:\t\n  mode: slowOp\t\n  slowOpThresholdMs: 200\n"
      containerSecurityContext:
        allowPrivilegeEscalation: false
        capabilities:
          drop:
            - ALL
        seccompProfile:
          type: RuntimeDefault
      expose:
        enabled: true
        type: NodePort
      name: rs0
      nodeSelector:
        openebs.io/localpv: 'true'
      nonvoting:
        affinity:
          antiAffinityTopologyKey: kubernetes.io/hostname
        enabled: false
        podDisruptionBudget:
          maxUnavailable: 1
        resources:
          limits:
            cpu: 300m
            memory: 0.5G
          requests:
            cpu: 300m
            memory: 0.5G
        size: 0
        volumeSpec:
          persistentVolumeClaim:
            resources:
              requests:
                storage: 3Gi
      podDisruptionBudget:
        maxUnavailable: 1
      podSecurityContext:
        fsGroup: 2
        fsGroupChangePolicy: OnRootMismatch
        runAsGroup: 2
        runAsNonRoot: true
        runAsUser: 2
      resources:
        limits:
          cpu: '1'
          memory: 2G
        requests:
          cpu: 300m
          memory: 2G
      serviceAccountName: percona-server-mongodb-operator
      size: 3
      storage:
        engine: wiredTiger
        inMemory:
          engineConfig:
            inMemorySizeRatio: 0.5
        wiredTiger:
          collectionConfig:
            blockCompressor: snappy
          engineConfig:
            cacheSizeRatio: 0.5
            directoryForIndexes: false
            journalCompressor: snappy
          indexConfig:
            prefixCompression: true
      terminationGracePeriodSeconds: 300
      volumeSpec:
        persistentVolumeClaim:
          resources:
            requests:
              storage: 25Gi
          storageClassName: openebs-lvmpv-xfs
  secrets:
    users: mongodb-cms-secrets
  
  tls:
    allowInvalidCertificates: true
    certValidityDuration: 2160h
    issuerConf:
      group: cert-manager.io
      kind: ClusterIssuer
      name: self-signed-cert-issuer
    mode: preferTLS
  unmanaged: false
  unsafeFlags:
    backupIfUnhealthy: false
    mongosSize: false
    replsetSize: false
    terminationGracePeriod: false
    tls: false
  updateStrategy: SmartUpdate
  upgradeOptions:
    apply: disabled
    schedule: 0 2 * * *
    setFCV: false
    versionServiceEndpoint: https://check.percona.com

```
