### ISSUE TITLE
Feature Request: CRDs for provisioning Databases with code.

### ISSUE THREAD

**Issue by devantler** [percona/everest#574]
I just saw your [blog post on the CNCF blog](https://www.cncf.io/blog/2024/07/26/the-inevitable-kubernetes-10-years-still-a-lot-to-do/), and wanted to check out Everest. It looks really promising, and I say that as a person who have deliberately choosen to use Managed Databases over self-hosted databases for quite some time, as I still feel there is a large amount of risk in self-hosting these (largely due to the complexity of doing so, and the resulting risk of failing to do it right).

I understand the need to simplify provisioning of databases by providing a UI, but I am a big GitOps fan, and thus I prefer to keep all my infrastructure as code. Have you considered CRDs as an alternative API for provisioning Databases with Everest? Applying something like this while knowing Everest handles all my concerns would be awesome:

```yaml
apiVersion: database.everest.io/v1
kind: Database
metadata:
  name: postgres
spec:
  database:
    type: postgresql
    ...
  backups:
    frequency: 3h
    store: some-url-to-a-blob-store
    ...
```

Ideally the CRDs would provide all the same options as found in the UI.

I believe this would make Everest fit better into GitOps workflows as that assumes raw manifests to be the primary API for configuring all things running in the cluster. Having many UIs in such a setup actually makes everything much more complicated, as one of the benefits of not having to visit UIs to make configurations is that you can provision everything from scratch, which is quite nice for CI/CD, and in general.

If you are considering this approach, I might also suggest to make it complimentary to the UI, such that any Database applied from code, shows in the UI, and such that any database created in the UI has its own CR applied.
